name: Build and Publish Release

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run compile

      - name: Run Linter
        run: npm run lint

      - name: Install latest version of @vscode/vsce
        run: npm install -g @vscode/vsce@latest

      - name: Package VSIX
        run: npx vsce package

      - name: Get package version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG_NAME=v$VERSION" >> $GITHUB_ENV

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create Tag
        if: env.TAG_EXISTS == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${{ env.VERSION }}" -m "Release v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"

      - name: Create Release
        if: env.TAG_EXISTS == 'false'
        uses: softprops/action-gh-release@v2
        with:
          files: sagemath-enhanced-${{ env.VERSION }}.vsix
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          generate_release_notes: true
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            ## Release v${{ env.VERSION }}
            
            This release was automatically generated from the main branch.
            
            ### Changes
            See the auto-generated release notes below for details.
            
            ### Installation
            Download the `sagemath-enhanced-${{ env.VERSION }}.vsix` file and install it in VS Code using:
            ```
            code --install-extension sagemath-enhanced-${{ env.VERSION }}.vsix
            ```

      - name: Skip Release (Tag Already Exists)
        if: env.TAG_EXISTS == 'true'
        run: |
          echo "Tag v${{ env.VERSION }} already exists. Skipping release creation."
          echo "If you want to create a new release, please update the version in package.json"
